name: SwiftLint

on:
  push:
  pull_request:
    types:
      - opened

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
